export interface ProductSpec {
  key: string
  value: string
}

export interface Product {
  slug: string
  name: string
  category: string
  categoryLabel: string
  tagline: string
  description: string
  features: string[]
  specs: ProductSpec[]
  images: string[]
  type: 'shop' | 'inquiry'
  variants?: { label: string; price?: string }[]
  detailImages?: string[]
}

export const products: Product[] = [
  {
    slug: 'bms-protection-board',
    name: 'BMS Protection Board',
    category: 'bms',
    categoryLabel: 'BMS Protection Board',
    tagline: 'Intelligent battery management for optimal performance',
    description:
      'Comprehensive BMS solutions from JK — covering active balancers (2A~15A), protection boards (40A~300A), and parallel boards with integrated current limiters. Supports 4S to 32S cell configurations for LFP, NMC, LMO, LTO batteries. Features CAN/RS485/Bluetooth communication, real-time monitoring, and GPS-ready options for energy storage, EV, and industrial applications.',
    features: [
      'Active Balancers: JK-B2A8S~JK-B15A24S — 2A to 15A balancing current, 4S~24S support',
      'Protection Boards: JK-BD/B1A/B2A series — 40A to 300A continuous, 4S~32S',
      'Parallel Boards (PB series): Integrated 10A parallel current-limiting module',
      'Relay Versions (RP series): 25S/32S with integrated pre-charge, supports same-port',
      'CAN / RS485 / isoSPI daisy-chain communication with PCS & EMS',
      'Real-time voltage (±5mV) & temperature monitoring with Bluetooth option',
      'Overcharge / over-discharge / over-temperature / short-circuit protection',
      'GPS-ready models (G102-4G) and USB-TTL isolated communication',
    ],
    specs: [
      { key: 'Cell Range', value: '4S ~ 32S (12V ~ 96V)' },
      { key: 'Balancing Current', value: '0.4A ~ 15A (active balancing)' },
      { key: 'Continuous Current', value: '40A ~ 300A (varies by model)' },
      { key: 'Communication', value: 'CAN 2.0 / RS485 / Bluetooth / isoSPI' },
      { key: 'Compatible Chemistries', value: 'LFP, NMC, LMO, LTO' },
      { key: 'Protection', value: 'Overcharge, over-discharge, over-temp, short-circuit' },
      { key: 'Operating Temp', value: '-20°C ~ 65°C' },
      { key: 'Accessories', value: 'LCD displays, GPS 4G, shunt, adapters, cables' },
    ],
    images: [
      '/images/bms-board/1.jpg',
      '/images/bms-board/2.jpg',
      '/images/bms-board/3.jpg',
      '/images/bms-board/4.jpg',
      '/images/bms-board/5.jpg',
      '/images/bms-board/6.jpg',
    ],
    detailImages: [
      '/images/bms-board-detail/1.jpg',
      '/images/bms-board-detail/2.jpg',
      '/images/bms-board-detail/3.jpg',
      '/images/bms-board-detail/4.jpg',
      '/images/bms-board-detail/5.jpg',
      '/images/bms-board-detail/6.jpg',
      '/images/bms-board-detail/7.jpg',
      '/images/bms-board-detail/8.jpg',
      '/images/bms-board-detail/9.jpg',
      '/images/bms-board-detail/10.jpg',
      '/images/bms-board-detail/11.jpg',
      '/images/bms-board-detail/12.jpg',
    ],
    type: 'shop',
    variants: [
      { label: '16S 48V 200A', price: '$189.00' },
      { label: '16S 48V 300A', price: '$259.00' },
      { label: '20S 72V 200A', price: '$229.00' },
    ],
  },
  {
    slug: 'battery-kit',
    name: 'Battery Kit (With Caster)',
    category: 'battery-kit',
    categoryLabel: 'Battery Kit (With Caster)',
    tagline: 'Complete energy storage solution on wheels, ready to deploy',
    description:
      'The JKESS Roller Battery Kit is a portable energy storage system built on a heavy-duty caster base for easy mobility. It features a robust sheet-metal enclosure, integrated BMS with LCD, and supports both 15KWh and 16KWh LFP cells. Ideal for home backup, mobile power, and small commercial applications requiring flexibility and quick deployment.',
    features: [
      'Heavy-duty caster wheels — easy to move and position, perfect for mobile power needs',
      'Sheet-metal enclosure — durable, IP54 rated for indoor & semi-outdoor use',
      'Dual compatibility — supports both 15KWh & 16KWh LFP cells (280Ah ~ 320Ah)',
      'Integrated BMS with LCD display — real-time monitoring of voltage, current & SOC',
      'Pre-assembled and tested — plug-and-play installation, ready out of the box',
      'Scalable design — connect multiple units for larger capacity requirements',
      'CAN / RS485 communication — integrates with inverters and monitoring systems',
      '5-year warranty — backed by JKBMS quality assurance',
    ],
    specs: [
      { key: 'Capacity', value: '15KWh / 16KWh' },
      { key: 'Configuration', value: 'Box + BMS + LCD + Caster Base' },
      { key: 'Compatible Cells', value: '280Ah ~ 320Ah LFP (LiFePO4)' },
      { key: 'Enclosure', value: 'Sheet-metal, IP54 rated' },
      { key: 'Dimensions', value: '584 × 346 × 210 mm' },
      { key: 'Weight', value: '~28 kg (empty)' },
      { key: 'Mobility', value: '4 heavy-duty caster wheels (2 with brakes)' },
      { key: 'Communication', value: 'CAN 2.0 / RS485' },
      { key: 'Display', value: 'LCD touch screen' },
      { key: 'Cycle Life', value: '6000+ cycles @ 80% DOD' },
      { key: 'Warranty', value: '5 years' },
    ],
    images: [
      '/images/battery-kit-hero.webp',
      '/images/battery-kit-system.webp',
      '/images/battery-kit-front.webp',
      '/images/battery-kit-side.webp',
      '/images/battery-kit-rear.webp',
      '/images/battery-kit-display.webp',
    ],
    type: 'shop',
    variants: [
      { label: 'BOX and LCDBMS', price: '$400.00' },
      { label: 'OnlyBOX', price: '$250.00' },
    ],
    detailImages: [
      '/images/battery-kit-detail/1.webp',
      '/images/battery-kit-detail/2.webp',
      '/images/battery-kit-detail/3.webp',
      '/images/battery-kit-detail/4.webp',
      '/images/battery-kit-detail/5.webp',
      '/images/battery-kit-detail/6.webp',
      '/images/battery-kit-detail/7.webp',
      '/images/battery-kit-detail/8.webp',
      '/images/battery-kit-detail/9.webp',
      '/images/battery-kit-detail/10.webp',
      '/images/battery-kit-detail/11.webp',
      '/images/battery-kit-detail/12.webp',
      '/images/battery-kit-detail/13.webp',
      '/images/battery-kit-detail/14.webp',
      '/images/battery-kit-detail/15.webp',
      '/images/battery-kit-detail/16.webp',
      '/images/battery-kit-detail/17.webp',
      '/images/battery-kit-detail/18.webp',
    ],
  },
  {
    slug: 'high-voltage-kit',
    name: 'High Voltage Kit',
    category: 'high-voltage-kit',
    categoryLabel: 'High Voltage Kit',
    tagline: 'Industrial-grade high voltage energy storage',
    description:
      'Complete high-voltage BMS solution featuring BCU-B3 master control module & BMU-H5-16 active balancing slave modules. ISO 26262 functional safety design with 1500V detection, active balancing, and smart SOC/SOH/SOP estimation for industrial energy storage.',
    features: [
      'BCU-B3 Master Control: ISO 26262 functional safety, 1500V max detection',
      'BMU-H5-16 Active Balancing: ±5mV accuracy, 2A bidirectional active balancing',
      'SOC / SOH / SOP smart estimation based on physical cell model',
      '9~16 series cell voltage + 8-channel temperature collection per slave',
      'Remote OTA upgrades & real-time IoT cloud monitoring',
      'Multi-level power isolation, high EMC immunity',
      'CAN / RS485 / isoSPI daisy-chain communication with PCS & EMS',
      'Supports LFP, NMC, LMO, LTO battery types, GPS/BeiDou positioning',
    ],
    specs: [
      { key: 'Master Control', value: 'BCU-B3 — ISO 26262, 1500V detection' },
      { key: 'Slave Control', value: 'BMU-H5-16 — 16-cell, 2A active balancing' },
      { key: 'Voltage Accuracy', value: '±5mV (BMU) / ≤1% (BCU total voltage)' },
      { key: 'Current Detection', value: '-300A ~ +300A, ≤1% accuracy' },
      { key: 'Insulation', value: '≥20MΩ, high-voltage interlock' },
      { key: 'Communication', value: 'CAN ×2 / RS485 ×4 / isoSPI daisy-chain' },
      { key: 'Operating Temp', value: '-25°C ~ +85°C (BCU & BMU)' },
      { key: 'Protection', value: 'Overcharge/over-discharge/over-temp/fault alarm' },
    ],
    images: [
      '/images/hv-kit/1.jpg',
      '/images/hv-kit/2.jpg',
      '/images/hv-kit/3.jpg',
      '/images/hv-kit/4.jpg',
      '/images/hv-kit/5.jpg',
      '/images/hv-kit/6.jpg',
    ],
    detailImages: [
      '/images/hv-kit-detail/20.jpg',
      '/images/hv-kit-detail/1.jpg',
      '/images/hv-kit-detail/2.jpg',
      '/images/hv-kit-detail/3.jpg',
      '/images/hv-kit-detail/4.jpg',
      '/images/hv-kit-detail/5.jpg',
      '/images/hv-kit-detail/6.jpg',
      '/images/hv-kit-detail/7.jpg',
      '/images/hv-kit-detail/8.jpg',
      '/images/hv-kit-detail/9.jpg',
      '/images/hv-kit-detail/10.jpg',
      '/images/hv-kit-detail/12.jpg',
      '/images/hv-kit-detail/13.jpg',
      '/images/hv-kit-detail/14.jpg',
      '/images/hv-kit-detail/15.jpg',
      '/images/hv-kit-detail/16.jpg',
      '/images/hv-kit-detail/17.jpg',
      '/images/hv-kit-detail/18.jpg',
      '/images/hv-kit-detail/19.jpg',
    ],
    type: 'inquiry',
  },
  {
    slug: '6u-battery-kit',
    name: '6U Battery Kit',
    category: 'battery-kit',
    categoryLabel: '6U Battery Kit',
    tagline: 'Rack-mount energy storage for professional installations',
    description:
      'The JKESS 6U Battery Kit (JKLU015) is a professional-grade energy storage system designed for standard 19-inch rack-mount installations. It features high-energy-density LFP cells, an intelligent BMS with active balancing, and a 4.3-inch LCD display for real-time monitoring. Suitable for residential solar backup, commercial peak shaving, telecom backup, and off-grid applications.',
    features: [
      '6U rack-mount form factor — fits standard 19-inch cabinets for easy integration',
      'Modular parallel design — easy to expand capacity up to 30KWh or more',
      'Intelligent BMS with active cell balancing — extends battery life up to 20%',
      '4.3-inch LCD display — real-time voltage, current, temperature & SOC monitoring',
      'CAN / RS485 communication — seamless integration with inverters and monitoring systems',
      'Modular parallel design — expandable up to 30KWh or more for larger capacity',
      'Compatible with leading inverters — works with Victron, Growatt, Deye, Sofar, and more',
      '5-year warranty — backed by JKBMS quality assurance',
    ],
    specs: [
      { key: 'Model', value: 'JKLU015' },
      { key: 'Nominal Capacity', value: '15KWh' },
      { key: 'Nominal Voltage', value: '51.2V' },
      { key: 'Form Factor', value: '6U Rack-mount (19-inch)' },
      { key: 'Cell Chemistry', value: 'LiFePO4 (LFP)' },
      { key: 'Cycle Life', value: '6000+ cycles @ 80% DOD' },
      { key: 'Communication', value: 'CAN 2.0 / RS485' },
      { key: 'Display', value: '4.3-inch LCD Touch' },
      { key: 'Operating Temp', value: '-20°C ~ 60°C' },
      { key: 'Protection Rating', value: 'IP20 (indoor)' },
      { key: 'Weight', value: '~45 kg' },
      { key: 'Warranty', value: '5 years' },
    ],
    images: [
      '/images/6u-kit/1.webp',
      '/images/6u-kit/2.webp',
      '/images/6u-kit/3.webp',
      '/images/6u-kit/4.webp',
      '/images/6u-kit/5.webp',
      '/images/6u-kit/6.webp',
    ],
    detailImages: [
      '/images/6u-kit-detail/1.webp',
      '/images/6u-kit-detail/2.webp',
      '/images/6u-kit-detail/3.webp',
      '/images/6u-kit-detail/4.webp',
      '/images/6u-kit-detail/5.webp',
      '/images/6u-kit-detail/6.webp',
      '/images/6u-kit-detail/7.webp',
      '/images/6u-kit-detail/8.webp',
      '/images/6u-kit-detail/9.webp',
      '/images/6u-kit-detail/10.webp',
      '/images/6u-kit-detail/11.webp',
      '/images/6u-kit-detail/12.webp',
      '/images/6u-kit-detail/13.webp',
      '/images/6u-kit-detail/14.webp',
      '/images/6u-kit-detail/15.webp',
      '/images/6u-kit-detail/16.webp',
    ],
    type: 'shop',
    variants: [
      { label: 'BOX and LCDBMS', price: '$400.00' },
      { label: 'OnlyBOX', price: '$250.00' },
    ],
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug)
}
